sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mv src/environments/environment.sample.ts src/environments/environment.ts

before_script:
  - npm install -g @angular/cli@1.0.0-rc.4
  - npm install -g karma
  - npm install -g typescript@2.0.0
  - npm install
  - ng build

script: ng test --single-run